// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrojkfmsYm-tHHbr3kF0n_mNMG-tgWh4M',
    appId: '1:535812212821:web:4e944cd215e0d2e8d42cdc',
    messagingSenderId: '535812212821',
    projectId: 'fureverhome-c4780',
    authDomain: 'fureverhome-c4780.firebaseapp.com',
    storageBucket: 'fureverhome-c4780.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3coeWNPQNjNl2SoAPsclnYLmbGA3mGVg',
    appId: '1:535812212821:android:8fce08406885401ed42cdc',
    messagingSenderId: '535812212821',
    projectId: 'fureverhome-c4780',
    storageBucket: 'fureverhome-c4780.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6hzMzNUQ09HAidMIKYV_cZ3lVJK-I9XU',
    appId: '1:535812212821:ios:fe4a4b7a3d9ec5c8d42cdc',
    messagingSenderId: '535812212821',
    projectId: 'fureverhome-c4780',
    storageBucket: 'fureverhome-c4780.firebasestorage.app',
    iosBundleId: 'com.example.fureverhome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6hzMzNUQ09HAidMIKYV_cZ3lVJK-I9XU',
    appId: '1:535812212821:ios:fe4a4b7a3d9ec5c8d42cdc',
    messagingSenderId: '535812212821',
    projectId: 'fureverhome-c4780',
    storageBucket: 'fureverhome-c4780.firebasestorage.app',
    iosBundleId: 'com.example.fureverhome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrojkfmsYm-tHHbr3kF0n_mNMG-tgWh4M',
    appId: '1:535812212821:web:c2eab6f6c8337e3dd42cdc',
    messagingSenderId: '535812212821',
    projectId: 'fureverhome-c4780',
    authDomain: 'fureverhome-c4780.firebaseapp.com',
    storageBucket: 'fureverhome-c4780.firebasestorage.app',
  );
}
